services:
  db:
    image: postgres:16
    container_name: gymtracker_db
    restart: always
    environment:
      POSTGRES_DB: gymtracker_db
      POSTGRES_USER: gymtracker_user
      POSTGRES_PASSWORD: securepassword1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gymtracker_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: gymtracker_db
      POSTGRES_USER: gymtracker_user
      POSTGRES_PASSWORD: securepassword1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
