# For local development and testing (Independent of production setup)
name: gymtracker

services:
  db:
    image: postgres:16
    container_name: gymtracker_db
    restart: always
    environment:
      POSTGRES_DB: gymtracker_db
      POSTGRES_USER: gymtracker_user
      POSTGRES_PASSWORD: securepassword1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gymtracker_user -d gymtracker_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gymtracker_backend
    command: sh -c "python manage.py migrate 
      && python manage.py import_exercises 
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: gymtracker_db
      POSTGRES_USER: gymtracker_user
      POSTGRES_PASSWORD: securepassword1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: secretkey1234
      DEBUG: 'True'

volumes:
  postgres_data:
